[package]
name = "map_craft"
version = "0.1.0"
authors = ["Eric Mikulin <ericm99@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3.4"
clap = {version = "2.33.1", features = ["yaml"]}
hematite-nbt = "0.5.0"
indicatif = "0.15.0"
lazy_static = "1.4.0"
nom = "5.1.2"
serde_json = "1.0.59"
